package com.model.pojo;
// Generated Jun 8, 2020 7:38:27 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Survey generated by hbm2java
 */
@Entity
@Table(name="survey"
    ,catalog="surveymhs"
)
public class Survey  implements java.io.Serializable {


     private String nama;
     private String email;
     private String alamat;
     private String kota;
     private String negBag;
     private String pos;
     private Date tgl;
     private String suka;
     private String how;
     private String rekomendasi;
     private String komentar;

    public Survey() {
    }

	
    public Survey(String nama) {
        this.nama = nama;
    }
    public Survey(String nama, String email, String alamat, String kota, String negBag, String pos, Date tgl, String suka, String how, String rekomendasi, String komentar) {
       this.nama = nama;
       this.email = email;
       this.alamat = alamat;
       this.kota = kota;
       this.negBag = negBag;
       this.pos = pos;
       this.tgl = tgl;
       this.suka = suka;
       this.how = how;
       this.rekomendasi = rekomendasi;
       this.komentar = komentar;
    }
   
     @Id 

    
    @Column(name="nama", unique=true, nullable=false)
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }

    
    @Column(name="email")
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="alamat")
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }

    
    @Column(name="kota")
    public String getKota() {
        return this.kota;
    }
    
    public void setKota(String kota) {
        this.kota = kota;
    }

    
    @Column(name="negBag")
    public String getNegBag() {
        return this.negBag;
    }
    
    public void setNegBag(String negBag) {
        this.negBag = negBag;
    }

    
    @Column(name="pos")
    public String getPos() {
        return this.pos;
    }
    
    public void setPos(String pos) {
        this.pos = pos;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="tgl", length=10)
    public Date getTgl() {
        return this.tgl;
    }
    
    public void setTgl(Date tgl) {
        this.tgl = tgl;
    }

    
    @Column(name="suka")
    public String getSuka() {
        return this.suka;
    }
    
    public void setSuka(String suka) {
        this.suka = suka;
    }

    
    @Column(name="how")
    public String getHow() {
        return this.how;
    }
    
    public void setHow(String how) {
        this.how = how;
    }

    
    @Column(name="rekomendasi")
    public String getRekomendasi() {
        return this.rekomendasi;
    }
    
    public void setRekomendasi(String rekomendasi) {
        this.rekomendasi = rekomendasi;
    }

    
    @Column(name="komentar")
    public String getKomentar() {
        return this.komentar;
    }
    
    public void setKomentar(String komentar) {
        this.komentar = komentar;
    }


//This method writes the values of contact object with System.out.println(user.toString()) code  
    @Override  
    public String toString()  
    {  
        return "survey" +  
            "\n\t Nama: " + this.nama +  
            "\n\t Email: " + this.email +  
            "\n\t Alamat: " + this.alamat +  
            "\n\t Kota: " + this.kota +  
            "\n\t Negara Bagian: " + this.negBag +  
            "\n\t Kode Pos: " + this.pos + 
            "\n\t Tanggal Survey: " + this.tgl +  
            "\n\t Apa yang Disukai: " + this.suka +  
            "\n\t Bagaimana Tertarik: " + this.how +  
            "\n\t Rekomendasikan UNDIP: " + this.rekomendasi +  
            "\n\t Komentar: " + this.komentar;
    }  

}


